// Hollowtree — single source of truth for tuning constants.

export const FLIGHT = {
  maxSpeed: 12,
  boostSpeed: 19,
  accel: 24,
  boostAccel: 36,
  drag: 1.6,
  liftSpeed: 8,
  liftAccel: 24,
  turnRate: 4.2,
  bankMax: 0.6,
  bankResponse: 5.5,
  pitchMax: 0.42,
  hoverBobAmp: 0.016,
  hoverBobFreq: 5.4,
  minAltitude: 0.45,
  maxAltitude: 90,
  bodyRadius: 0.35,
  dragQuad: 0.022,
  speedCapResponse: 26.0,
  boostResponse: 4.5,
  boostSurge: 1.55,
  boostSurgeDecay: 2.6,
  liftDamp: 1.6,
  liftIdleDamp: 1.1,
  liftSpool: 9.0,
  turnSharpness: 7.0,
  turnSmoothing: 12.0,
  turnRateBoost: 1.3,
  bankFromTurn: 0.024,
  bankFromStrafe: 0.46,
  pitchFromAccel: 0.014,
  pitchFromClimb: 0.038,
  pitchFromThrottle: 0.1,
  pitchResponse: 5.5,
  accelSmoothing: 9.0,
  hoverSpeedRange: 2.8,
  hoverBobFreqGain: 2.6,
  hoverBobResponse: 22.0,
  hoverWobbleAmp: 0.028,
  hoverWobbleFreq: 0.37,
  groundSpring: 55,
  groundPush: 18,
  groundAbsorb: 9,
  groundFriction: 2.4,
  groundMaxPenetration: 0.5,
  groundedBand: 0.12,
  ceilingDamp: 3.0,
  collisionSlide: 0.94,
  strafeScale: 1.0,
  reverseScale: 0.55,
  maxDt: 0.05,
};

export const CAMERA = {
  fov: 62,
  fovBoost: 73,
  fovResponse: 3.4,
  distance: 4.6,
  height: 1.35,
  lookAhead: 1.9,
  posStiffness: 12.0,
  posDamping: 1.0,
  rotStiffness: 11.0,
  bankInfluence: 0.38,
  near: 0.1,
  far: 800,
  mouseSensitivity: 0.0014,
  invertY: false,
  pitchMin: -1.15,
  pitchMax: 0.95,
  distanceSpeedGain: 1.5,
  distanceBoostGain: 0.7,
  heightSpeedGain: -0.3,
  accelLag: 0.022,
  accelLagMax: 0.9,
  accelLagResponse: 7.0,
  lookStiffness: 17.0,
  lookUp: 0.5,
  rollFromTurn: 0.035,
  rollResponse: 6.0,
  fovSpeedGain: 2.5,
  minGroundClearance: 0.85,
  shakeAmp: 0.016,
  shakeFreq: 17.0,
  maxDt: 0.05,
};

export const WORLD = {
  size: 900,
  segments: 220,
  hillHeight: 9.0,
  fogNear: 90,
  fogFar: 520,
};

export const GRASS = {
  count: 62000,
  radius: 120,
  bladeHeight: 0.82,
  windStrength: 0.13,
  windSpeed: 1.1,
  lodNear: 45,
  lodFar: 115,
};

export const RENDER = {
  targetFps: 40,
  maxPixelRatio: 1.5,
  shadowMapSize: 2048,
  // What the quality tiers actually cost. Pixel ratio dominates: a Retina panel at
  // 1.5 draws 2.25x the fragments of 1.0, which is the single biggest lever on an
  // integrated or mobile GPU. Shadows are the second.
  tiers: {
    performance: { pixelRatio: 1.0, shadowMapSize: 1024, shadows: true },
    balanced: { pixelRatio: 1.25, shadowMapSize: 2048, shadows: true },
    high: { pixelRatio: 1.5, shadowMapSize: 2048, shadows: true },
  },
  shadowRadius: 60,
  bloomStrength: 0.42,
  bloomRadius: 0.7,
  bloomThreshold: 0.82,
  toneMappingExposure: 1.06,
};

export const PALETTE = {
  sunWarm: 0xffe6b0,
  skyTop: 0x6fb2e8,
  skyHorizon: 0xdfe9d6,
  ground: 0x6f9a45,
  groundDry: 0x9aa15c,
  fog: 0xd8e3c8,
};

export const SKY = {
  domeRadius: 700,
  domeSegments: 32,
  fogDensity: 0.0016,
  sunIntensity: 2.35,
  hemiIntensity: 0.68,
  ambientIntensity: 0.26,
  sunElevationMin: 0.12,
  sunElevationMax: 0.42,
  sunAzimuth: 2.25,
  sunDistance: 160,
  defaultTimeOfDay: 0.58,
  // One in-game day in real milliseconds. Derived from the world clock, so every
  // client agrees on the light without syncing anything. A season is two real days
  // (NET.season), so this gives roughly 64 dawns per season — short enough that a
  // 20-minute visit sees the light move, long enough that it is not a strobe.
  dayLengthMs: 45 * 60 * 1000,
  horizonSoftness: 0.72,
  glowStrength: 0.55,
  discSharpness: 900.0,
  shadowBias: -0.0005,
  shadowNormalBias: 0.04,
  shadowNear: 1.0,
  shadowFar: 340,
  sunHorizonColor: 0xffb35e,
  hemiGround: 0x6a5c33,
  ambientColor: 0xbcd2e8,
};

export const TERRAIN = {
  seed: 1337,
  noiseScale: 0.0041,
  octaves: 5,
  lacunarity: 2.03,
  gain: 0.5,
  ampBase: 1.35,
  ampRidge: 0.75,
  ampMid: 0.5,
  warpStrength: 24,
  warpScale: 0.0019,
  clearingRadius: 32,
  clearingFalloff: 40,
  aoBlurRadius: 6,
  aoStrength: 0.42,
  aoRange: 1.4,
  patchScale: 0.017,
  patchLow: 0.4,
  patchHigh: 0.74,
  patchDryness: 0.85,
  slopeDryness: 1.5,
  heightDryness: 0.35,
  tintScale: 0.09,
  tintStrength: 0.05,
  slopeShade: 0.3,
  sunTerrainTint: 0.1,
};

export const GRASS_DETAIL = {
  tiers: [
    { share: 0.34, tile: 42, fadeStart: 12, fadeEnd: 21, radial: false },
    { share: 0.30, tile: 76, fadeStart: 24, fadeEnd: 38, radial: false },
    { share: 0.21, tile: 134, fadeStart: 44, fadeEnd: 67, radial: false },
    { share: 0.15, tile: 240, fadeStart: 84, fadeEnd: 118, radial: true },
  ],
  fadeSoftness: 1.6,
  updatePerFrame: 5200,
  bladeWidth: 0.078,
  heightVariance: 0.42,
  farWidthBoost: 0.7,
  maxSlope: 0.8,
  rootShade: 0.34,
  midShade: 0.78,
  tipShade: 1.16,
  tintVariance: 0.11,
  dryMix: 0.35,
  colorLush: 0x598b30,
  colorDry: 0x93a04b,
  sink: 0.05,
  mergeNear: 34,
  mergeFar: 96,
  mergeTint: 1.12,
};

export const CLUTTER = {
  stoneCount: 150,
  stoneRadius: 85,
  stoneScale: 1.35,
  stoneJitter: 0.34,
  stoneColor: 0x9b9384,
  tuftCount: 560,
  tuftRadius: 70,
  tuftScale: 1.55,
  tuftColor: 0x6f8a33,
  updateInterval: 17,
};

export const LOOP = {
  fixedHz: 60,
  maxFrameTime: 0.2,
  maxSubSteps: 5,
  fpsSmoothing: 0.09,
};

export const INPUT = {
  mouseSensitivity: 0.00095,
  pitchClamp: 1.2,
  invertY: false,
  lookSmoothing: 0.26,
  gamepadDeadzone: 0.18,
  gamepadLookSpeed: 2.7,
};

export const DEV = {
  hudOpacity: 0.38,
  hudRefresh: 0.25,
  hintOpacity: 0.4,
};

export const FLOWERS = {
  seed: 20260804,
  count: 1050,
  radius: 150,
  clearRadius: 9.0,
  hiveClearRadius: 16.0,
  clusterCount: 88,
  clusterRadius: 8.0,
  clusterShare: 0.74,
  maxSlope: 0.85,
  placementTries: 6,
  cullDistance: 108,
  cullJitter: 0.26,
  fadeSoftness: 9.0,
  lodNear: 40,
  lodFar: 100,
  farWidthBoost: 0.34,
  updatePerFrame: 150,
  gridCell: 12,
  windStrength: 0.045,
  windSpeed: 1.1,
  swayCurve: 1.3,
  sink: 0.06,
  scaleVariance: 0.26,
  castShadow: true,
  modelPath: 'assets/models/',
  spentColor: 0x7d7460,
  spentFade: 0.86,
  tintVariance: 0.09,
  curlAmount: 0.44,
  curlDroop: 0.19,
  reserveEpsilon: 0.02,
};

export const FLOWER_SPECIES = [
  {
    id: 'meadow-daisy',
    name: 'meadow daisy',
    geometry: 'daisy',
    share: 0.34,
    zone: 0,
    bloom: { start: 0.08, end: 0.86 },
    colors: { petal: 0xfdf3e0, tip: 0xffffff, core: 0xf2b93c, stem: 0x4f7c34 },
    pollen: 3.0,
    nectar: 1.0,
    resin: 0,
    reserve: 6.0,
    regrowth: 0.30,
    regrowDelay: 4.0,
    scale: 1.00,
    petals: 9,
    model: 'flower-daisy.glb',
    headAnchor: 'head',
    height: 4.6,
    headHeight: 4.05,
    headRadius: 1.15,
    spread: 1.5,
    heads: 3,
    triBudget: 170,
  },
  {
    id: 'red-clover',
    name: 'red clover',
    geometry: 'clover',
    share: 0.30,
    zone: 0,
    bloom: { start: 0.16, end: 0.78 },
    colors: { petal: 0xd8618f, tip: 0xf0a2c0, core: 0xb44a78, stem: 0x4a7530 },
    pollen: 1.2,
    nectar: 3.4,
    resin: 0,
    reserve: 7.5,
    regrowth: 0.24,
    regrowDelay: 5.5,
    scale: 0.92,
    petals: 0,
    model: 'flower-clover.glb',
    headAnchor: 'head',
    height: 3.9,
    headHeight: 3.35,
    headRadius: 0.85,
    spread: 1.7,
    heads: 4,
    triBudget: 150,
  },
  {
    id: 'harebell',
    name: 'harebell',
    geometry: 'bell',
    share: 0.22,
    zone: 1,
    bloom: { start: 0.28, end: 0.92 },
    colors: { petal: 0x7f9fe0, tip: 0xb9cdf2, core: 0x5d78bd, stem: 0x51763a },
    pollen: 1.8,
    nectar: 2.4,
    resin: 0,
    reserve: 5.0,
    regrowth: 0.34,
    regrowDelay: 3.2,
    scale: 1.06,
    petals: 6,
    model: 'flower-harebell.glb',
    headAnchor: 'head',
    height: 6.3,
    headHeight: 5.2,
    headRadius: 0.7,
    spread: 1.1,
    heads: 5,
    triBudget: 150,
  },
  {
    // The only source of resin in the game, and therefore the gate on every comb cell.
    // The master prompt puts resin on conifers; until an authored conifer model exists
    // this is a spruce sapling standing in the meadow, gathered exactly like a bloom.
    // It carries no pollen and no nectar, so it is a detour with a purpose rather than
    // a strictly better flower, and it regrows slowest of the four.
    id: 'spruce-seep',
    name: 'spruce seep',
    geometry: 'conifer',
    share: 0.14,
    zone: 0,
    bloom: { start: 0.0, end: 1.0 },
    colors: { petal: 0x2f4a2a, tip: 0x3c5c33, core: 0xc98a3c, stem: 0x4a3a24 },
    pollen: 0,
    nectar: 0,
    resin: 3.2,
    reserve: 6.5,
    regrowth: 0.14,
    regrowDelay: 9.0,
    scale: 1.35,
    petals: 0,
    model: 'flower-spruce.glb',
    headAnchor: 'head',
    height: 7.2,
    headHeight: 4.6,
    headRadius: 1.5,
    spread: 0.9,
    heads: 3,
    triBudget: 180,
  },
];

export const RESOURCES = {
  kinds: ['pollen', 'nectar', 'resin'],
  capacity: { pollen: 999, nectar: 999, resin: 999 },
  start: { pollen: 0, nectar: 0, resin: 0 },
};

export const GATHER = {
  range: 3.4,
  verticalRange: 2.8,
  hoverSpeed: 2.6,
  breakSpeed: 4.4,
  rate: 1.5,
  windUp: 0.28,
  windDown: 3.2,
  basketCapacity: 22,
  depositCooldown: 0.6,
  promptRange: 6.5,
};

export const HIVE = {
  x: 0,
  z: -30,
  trunkHeight: 74.0,
  trunkRadiusBase: 7.4,
  trunkRadiusTop: 2.2,
  trunkSegments: 11,
  rootFlare: 1.75,
  rootHeight: 7.0,
  entranceHeight: 16.0,
  entranceRadius: 3.2,
  entranceDepth: 1.9,
  triggerRadius: 5.2,
  branchCount: 5,
  branchLength: 19.0,
  branchRadius: 1.5,
  canopyCount: 7,
  canopyRadius: 15.5,
  canopyHeight: 63.0,
  canopySpread: 12.5,
  swayAmp: 0.012,
  swaySpeed: 0.34,
  glowPulse: 0.35,
  model: 'hollow-tree.glb',
  entranceAnchor: 'entrance',
  canopyNode: 'canopy',
  colliderRadius: 0.78,
  rootColliderRadius: 1.5,
  glowColor: 0xffc46a,
  glowRadius: 0.66,
  colors: {
    bark: 0x6b503a,
    barkDark: 0x4a3728,
    hollow: 0x1b120c,
    lip: 0x86664a,
    canopy: 0x527a35,
    canopyDark: 0x3d5c27,
  },
};

export const HUD = {
  fadeIn: 0.35,
  fadeOut: 0.9,
  barResponse: 9.0,
  counterResponse: 7.5,
  pulseDuration: 0.6,
  idleHideDelay: 2.4,
  colors: {
    text: '#f7ead2',
    dim: 'rgba(247,234,210,.44)',
    pollen: '#f6c95a',
    nectar: '#e98d4e',
    resin: '#b7784a',
    honey: '#ffd98a',
  },
  copy: {
    gather: 'hold E to gather',
    steady: 'slow down to gather',
    holding: 'gathering',
    full: 'baskets full',
    deposit: 'fly into the hollow to deposit',
    deposited: 'stores replenished',
    spent: 'this bloom is spent',
  },
};

export const QUEEN = {
  scale: 1.0,
  wingColor: 0xf3f7ff,
  smearGhosts: 4,
  smearOpacity: 0.34,
  smearLag: 0.9,
  beatHz: 9.0,
  beatIdle: 0.25,
  beatSpeedGain: 0.7,
  beatBoostGain: 0.35,
  blurResponse: 4.0,
  sweepMin: 0.25,
  sweepMax: 0.62,
  sweepTwist: 0.35,
};

export const FLIGHT_FEEL = {
  throttleSpool: 15.0,
  strafeSpool: 11.0,
  strafeAccelScale: 1.06,
  bankStrafeFloor: 0.55,
  headingErrorMax: 0.34,
  headingErrorHard: 0.72,
  headingCatchUp: 24.0,
};

export const CAMERA_FRAME = {
  centerSoftAngle: 0.10,
  centerHardAngle: 0.17,
  centerFalloff: 0.35,
  aimHeight: 0.5,
  yawSpeedResponse: 12.0,
  yawStiffnessRef: 3.0,
  yawStiffnessGain: 0.55,
};

export const CLUTTER_EXCLUSION = {
  cell: 4.5,
  perCell: 5,
  stoneClearance: 1.08,
  boxPadding: 0.5,
  boxRange: 115,
  boxGroundBand: 2.0,
  boxMinSize: 2.5,
  maxBoxes: 24,
};

export const FOREST = {
  seed: 5150,
  count: 46,
  innerRadius: 128,
  outerRadius: 350,
  minHeight: 44,
  maxHeight: 90,
  trunkRadius: 0.062,
  trunkFlare: 1.6,
  trunkSegments: 7,
  trunkRows: 4,
  canopyPerTree: 3,
  canopyDetail: 0,
  canopyRadius: 0.23,
  canopyBase: 0.62,
  canopySpread: 0.15,
  canopySquash: 0.82,
  maxSlope: 0.9,
  colliderRange: 240,
  colliderRadius: 0.9,
  model: 'meadow-tree.glb',
  swayAmp: 0.0,
  colors: {
    bark: 0x5d452f,
    barkDark: 0x392a1c,
    canopy: 0x4a7030,
    canopyDark: 0x33501f,
  },
};

export const INTERIOR = {
  model: 'hollow',
  hallWidth: 96.0,
  hallDepth: 64.0,
  heightScale: 0.86,
  minHeight: 40.0,
  ceilingClearance: 8.0,
  floorLift: 3.2,
  wallThickness: 3.0,
  entranceMargin: 1.25,
  throatLength: 3.2,
  throatFlare: 1.35,
  segmentsLong: 16,
  segmentsShort: 11,
  segmentsUp: 12,
  landingWidth: 27.0,
  landingDepth: 11.0,
  landingThickness: 1.0,
  galleryTiers: 4,
  galleryStart: 0.17,
  galleryEnd: 0.86,
  ledgeDepth: 5.2,
  ledgeThickness: 0.7,
  ledgeRunLong: 0.56,
  ledgeRunShort: 0.66,
  alcoveWidth: 14.0,
  alcoveDepth: 10.5,
  alcoveTiers: 3,
  alcoveStart: 0.22,
  alcoveEnd: 0.80,
  pillarSize: 4.6,
  pillarSpanX: 0.46,
  pillarSpanZ: 0.40,
  skylightWidth: 11.0,
  skylightDepth: 8.5,
  skylightSpanX: 0.44,
  skylightSpanZ: 0.26,
  poolCount: 5,
  poolRadius: 4.4,
  knotCount: 8,
  knotWidth: 2.4,
  knotHeight: 1.5,
  knotBeamLength: 26.0,
  knotBeamSpread: 2.6,
  knotBeamOpacity: 0.11,
  dustCount: 520,
  dustSize: 0.13,
  dustDrift: 0.45,
  shaftOpacity: 0.1,
  fadeSpeed: 5.5,
  insideMargin: 1.4,
  cameraMargin: 1.7,
  hideDetailAt: 0.85,
  clipUntil: 0.62,
  clipLateral: 0.9,
  fogColor: 0x14100b,
  fogNear: 6.0,
  fogFar: 190.0,
  fogDensity: 0.0055,
  ambientColor: 0x8a6a44,
  ambientIntensity: 0.16,
  hemiSkyColor: 0x9fbde4,
  hemiGroundColor: 0xb87c3e,
  hemiIntensity: 0.62,
  entranceLightColor: 0xffd9a0,
  entranceLightIntensity: 110.0,
  entranceLightRange: 66.0,
  skylightLightColor: 0xdce8ff,
  skylightLightIntensity: 130.0,
  skylightLightRange: 82.0,
  crownLightColor: 0xe8d2a4,
  crownLightIntensity: 46.0,
  crownLightRange: 58.0,
  basinLightColor: 0xffab52,
  basinLightIntensity: 26.0,
  basinLightRange: 40.0,
  colors: {
    wall: 0x4a3423,
    wallDeep: 0x1d1410,
    wallLit: 0x8a6338,
    floor: 0x3a2a1c,
    ceiling: 0x2a1e14,
    ledge: 0x6a4d31,
    beam: 0x5a4128,
    pool: 0xd98c34,
    knot: 0xffcf84,
    shaftWarm: 0xffd79a,
    shaftCool: 0xbcd6ff,
    dust: 0xffe3b0,
  },
};

export const COMB = {
  cellWidth: 1.0,
  cellDepth: 0.55,
  layers: 4,
  rowPad: 1.2,
  wallOffset: 0.12,
  entranceClear: 1.6,
  maxCells: 4000,
};

export const SCREENS = {
  colors: {
    text: '#f7ead2',
    bright: '#fff3d8',
    dim: 'rgba(247,234,210,.42)',
    faint: 'rgba(247,234,210,.18)',
    honey: '#f2b544',
    pollen: '#f6c95a',
    ink: '#171007',
    panel: 'rgba(30,21,11,.52)',
    panelEdge: 'rgba(246,201,90,.16)',
    live: '#8fc46a',
    warn: '#e0813f',
    fail: '#d9604f',
  },
  veil: 'linear-gradient(102deg,rgba(19,13,6,.94) 0%,rgba(19,13,6,.78) 30%,rgba(19,13,6,.24) 58%,rgba(19,13,6,.5) 100%)',
  blurPx: 3,
  panelBlurPx: 20,
  enterDuration: 0.7,
  itemStagger: 0.055,
  fadeOut: 0.55,
};

export const MENU = {
  backdrop: {
    radius: 122,
    height: 40,
    lookHeight: 44,
    speed: 0.03,
    bobAmp: 2.4,
    bobSpeed: 0.11,
    fov: 42,
    frameOffset: 0.34,
    startAngle: 0.7,
    settleTime: 2.2,
  },
  copy: {
    eyebrow: 'a co-op hive',
    title: 'Hollowtree',
    tagline: 'Three queens, one hollow, one shared summer.',
    solo: 'Fly alone',
    host: 'Open a hollow',
    join: 'Join with a code',
    queen: 'Your queen',
    options: 'Options',
    back: 'Back',
    soloNote: 'The same world, just quieter.',
    hostNote: 'You get a code to hand out.',
    joinNote: 'Five characters, from whoever opened it.',
    joinPlaceholder: 'CODE',
    joinAction: 'Join',
    joinBadCode: 'That code is five letters and numbers.',
    queenColor: 'Colour',
    queenPattern: 'Marking',
    queenName: 'Name',
    queenNamePlaceholder: 'Queen',
    optionSensitivity: 'Mouse sensitivity',
    optionSensitivityNote: 'Also on [ and ] while flying.',
    optionMaster: 'Master volume',
    optionMusic: 'Music',
    optionSfx: 'Effects',
    optionQuality: 'Visual quality',
    optionQualityNote: 'Applies to bloom and depth of field.',
    footer: 'W A S D to fly · Space and Shift for height · E to gather',
  },
};

export const QUEEN_STYLE = {
  colors: [
    { id: 'amber', name: 'Amber', hex: '#f2b544', trim: '#7a4a17' },
    { id: 'ember', name: 'Ember', hex: '#e0713c', trim: '#6d2c14' },
    { id: 'clover', name: 'Clover', hex: '#8fc46a', trim: '#33511f' },
    { id: 'harebell', name: 'Harebell', hex: '#87a6e4', trim: '#2c3d6b' },
    { id: 'thistle', name: 'Thistle', hex: '#c58fd2', trim: '#4d2a58' },
    { id: 'linen', name: 'Linen', hex: '#f0e3c6', trim: '#6b5a3a' },
  ],
  patterns: [
    { id: 'banded', name: 'Banded' },
    { id: 'dusted', name: 'Dusted' },
    { id: 'sable', name: 'Sable' },
    { id: 'crowned', name: 'Crowned' },
  ],
  defaultColor: 'amber',
  defaultPattern: 'banded',
  defaultName: 'Queen',
  nameMaxLength: 14,
};

export const SETTINGS = {
  storageKey: 'hollowtree.settings',
  sensitivityMin: 0.0003,
  sensitivityMax: 0.006,
  qualityTiers: [
    { id: 'performance', name: 'Performance' },
    { id: 'balanced', name: 'Balanced' },
    { id: 'high', name: 'High' },
  ],
  defaults: {
    master: 0.8,
    music: 0.55,
    sfx: 0.85,
    quality: 'balanced',
  },
};

export const LOBBY = {
  maxPlayers: 3,
  codeLength: 10,
  codeAlphabet: 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789',
  stages: [
    { id: 'auth', label: 'Signing in', duration: 0.85 },
    { id: 'session', label: 'Opening the hollow', duration: 1.1 },
    { id: 'world', label: 'Reading the hive', duration: 1.35 },
    { id: 'ready', label: 'Warming the meadow', duration: 0.7 },
  ],
  fakeLatency: { min: 0.25, max: 0.8 },
  fakePeers: [
    { name: 'Ryszard', color: 'harebell', pattern: 'dusted', joinDelay: 3.4, readyDelay: 3.2 },
    { name: 'Marta', color: 'clover', pattern: 'crowned', joinDelay: 7.1, readyDelay: 4.6 },
  ],
  autoStartDelay: 1.4,
  failCode: 'ZZZZZ',
  copy: {
    hostingTitle: 'Your hollow is open',
    joiningTitle: 'Joining a hollow',
    soloTitle: 'Flying alone',
    codeLabel: 'Session code',
    copyAction: 'Copy',
    copiedAction: 'Copied',
    copyFailed: 'Press Cmd+C',
    shareNote: 'Anyone with this code can drop in, any time.',
    slotsLabel: 'Queens',
    empty: 'Waiting for a queen',
    emptySolo: 'Open — hand out the code',
    you: 'You',
    host: 'Host',
    ready: 'Ready',
    notReady: 'Settling in',
    readyAction: 'I am ready',
    unreadyAction: 'Hold on',
    enterAction: 'Enter the hollow',
    enterSoloAction: 'Fly out',
    waitingOthers: 'Waiting for the others',
    leaveAction: 'Leave',
    retryAction: 'Try again',
    statusConnecting: 'Connecting to the hive',
    statusLive: 'Live',
    statusRetrying: 'Lost the hive — reconnecting',
    statusOffline: 'No connection to the hive',
    failNetwork: 'Could not reach the hive. Your connection dropped or Firebase is unreachable.',
    failNoSession: 'No hollow with that code. It may have been closed.',
    failFull: 'That hollow already has three queens.',
    failGeneric: 'Something went wrong opening the session.',
    offlineAction: 'Fly alone instead',
    hint: 'The world keeps going between sessions — nothing here is lost when you leave.',
  },
};

export const POST = {
  enabled: true,
  tier: 'auto',
  startTier: 2,
  autoDegrade: true,
  warmup: 2.5,
  degradeGrace: 2.2,
  degradeTolerance: 1.22,
  frameSmoothing: 0.06,
  bypassTolerance: 2.4,
  allowBypass: true,
  tiers: [
    { motionTaps: 5, dof: false, bloom: false, fxaa: false, bloomScale: 0.3, renderScale: 0.85, motionDepthWeight: false },
    { motionTaps: 6, dof: false, bloom: true, fxaa: true, bloomScale: 0.32, renderScale: 1.0, motionDepthWeight: false },
    { motionTaps: 8, dof: true, bloom: true, fxaa: true, bloomScale: 0.4, renderScale: 1.0, motionDepthWeight: true },
    { motionTaps: 11, dof: true, bloom: true, fxaa: true, bloomScale: 0.5, renderScale: 1.0, motionDepthWeight: true },
  ],
  motion: {
    enabled: true,
    strength: 1.35,
    hoverFloor: 0.06,
    speedGain: 0.72,
    boostGain: 0.62,
    turnGain: 0.55,
    response: 9.0,
    maxRadius: 0.026,
    shutter: 1.0,
    dtRef: 1 / 60,
    dtClamp: 2.2,
    nearStart: 2.6,
    nearEnd: 11.0,
    jitter: 0.35,
    minPixels: 0.4,
  },
  dof: {
    focusDefault: 5.4,
    focusResponse: 4.5,
    focusMin: 1.2,
    focusMax: 140.0,
    range: 11.0,
    rangeInside: 3.4,
    falloff: 78.0,
    falloffInside: 22.0,
    nearFalloff: 5.5,
    nearFalloffInside: 2.6,
    radius: 2.4,
    radiusInside: 3.6,
    scale: 0.5,
    nearBleed: 0.62,
    maxBlend: 0.92,
  },
  bloom: {
    strengthInside: 0.56,
    thresholdInside: 0.7,
    insideResponse: 3.0,
  },
  grade: {
    contrast: 1.055,
    contrastGain: 1.045,
    saturation: 1.07,
    lift: 0.006,
    shadowTint: 0x8fa6c8,
    shadowAmount: 0.16,
    highlightTint: 0xffdda6,
    highlightAmount: 0.2,
    shadowEdge: 0.5,
    highlightEdge: 1.5,
    vignette: 0.3,
    vignetteSoftness: 0.42,
    vignetteInside: 0.46,
    sharpen: 0.3,
    sharpenClamp: 0.22,
    insideWarmth: 0.28,
    insideTint: 0xffc98a,
    seasonTint: 0xffffff,
    seasonMix: 0.0,
  },
};

export const CINEMATIC = {
  autoplay: true,
  autoplayDelay: 0.9,
  duration: 48.0,
  fadeIn: 1.35,
  fadeOut: 1.6,
  skipFade: 0.55,
  skipPromptDelay: 1.5,
  skipPromptFade: 0.6,
  letterbox: 0.118,
  letterboxIn: 1.15,
  letterboxOut: 1.25,
  driftCorrect: 0.45,
  maxDrift: 0.8,
  handheldAmp: 0.021,
  handheldFreq: 1.9,
  shakeAmp: 0.013,
  shakeFreq: 12.5,
  focusResponse: 6.0,
  copy: {
    skip: 'any key to skip',
    title: 'HOLLOWTREE',
    subtitle: 'a hive is built, not won',
  },
  cards: [
    { at: 2.0, dur: 4.6, fade: 1.0, text: 'title', size: 1.0 },
    { at: 44.2, dur: 3.2, fade: 1.0, text: 'subtitle', size: 0.36 },
  ],
  flashes: [
    { at: 17.2, dur: 0.62, peak: 0.92, color: '#fff4dd' },
    { at: 32.6, dur: 0.34, peak: 0.7, color: '#120a05' },
    { at: 39.4, dur: 0.42, peak: 0.86, color: '#0b0704' },
  ],
  shots: [
    { id: 'hatch_macro', at: 0.0, dur: 4.4, ease: 'holdOut', fov: [42, 34], shake: 0.0, handheld: 0.35 },
    { id: 'hatch_low', at: 4.4, dur: 3.8, ease: 'out', fov: [46, 40], shake: 0.18, handheld: 0.55 },
    { id: 'hatch_reveal', at: 8.2, dur: 5.4, ease: 'settle', fov: [44, 63], shake: 0.0, handheld: 0.25 },
    { id: 'launch', at: 13.6, dur: 3.6, ease: 'in', fov: [58, 70], shake: 0.28, handheld: 0.45 },
    { id: 'burst', at: 17.2, dur: 3.2, ease: 'out', fov: [52, 44], shake: 0.3, handheld: 0.5 },
    { id: 'chase', at: 20.4, dur: 5.2, ease: 'inOut', fov: [64, 71], shake: 0.35, handheld: 0.6 },
    { id: 'bloom', at: 25.6, dur: 3.8, ease: 'holdOut', fov: [37, 31], shake: 0.0, handheld: 0.3 },
    { id: 'meadow_wide', at: 29.4, dur: 3.2, ease: 'settle', fov: [50, 58], shake: 0.0, handheld: 0.2 },
    { id: 'hornets', at: 32.6, dur: 2.6, ease: 'linear', fov: [47, 51], shake: 0.55, handheld: 0.9 },
    { id: 'siege', at: 35.2, dur: 4.2, ease: 'inOut', fov: [49, 42], shake: 0.5, handheld: 1.0 },
    { id: 'retreat', at: 39.4, dur: 3.6, ease: 'out', fov: [57, 50], shake: 0.3, handheld: 0.7 },
    { id: 'flourish', at: 43.0, dur: 5.0, ease: 'settle', fov: [46, 65], shake: 0.0, handheld: 0.22 },
  ],
};

export const INTRO = {
  natalLateral: 12.0,
  natalDrop: 5.2,
  natalOffWall: 0.3,
  combPatchCols: 15,
  combPatchRows: 11,
  combCellRadius: 0.62,
  combCellDepth: 0.9,
  combPitch: 1.074,
  combRowRise: 0.93,
  capThickness: 0.14,
  capTremble: 0.055,
  capTrembleFreq: 9.0,
  capBreakAt: 4.6,
  capFall: 2.6,
  macroDist: 11.5,
  macroPush: 7.0,
  macroRise: 2.6,
  macroSlide: 4.2,
  lowDist: 3.8,
  lowDrop: 2.6,
  lowArc: 2.9,
  revealStart: 4.6,
  revealHeight: 0.42,
  revealBack: 0.58,
  emergeOut: 1.25,
  emergeWobble: 0.13,
  perchOut: 2.4,
  perchDrop: 3.2,
  perchDrift: 0.9,
  launchTrail: 3.4,
  launchAbove: 1.0,
  launchLead: 0.14,
  burstOut: 24.0,
  burstSide: 11.0,
  burstDrop: 15.0,
  burstDive: 46.0,
  chaseHeight: 5.2,
  chaseRun: 74.0,
  chaseWeave: 13.0,
  chaseOffsetBack: 4.0,
  chaseOffsetSide: 1.9,
  chaseOffsetUp: 0.7,
  bloomDist: 4.6,
  bloomPush: 2.15,
  bloomLift: 0.55,
  bloomOrbit: 0.5,
  wideStart: 16.0,
  wideEnd: 62.0,
  wideRise: 40.0,
  wideLook: 26.0,
  hornetPassHeight: 6.5,
  hornetPassSpan: 62.0,
  hornetPassLens: 9.0,
  siegeDist: 26.0,
  siegePush: 15.0,
  siegeDrop: 13.0,
  siegeSide: 7.0,
  guardCount: 14,
  guardArc: 2.15,
  guardRadius: 4.4,
  guardJitter: 0.34,
  guardJitterFreq: 3.1,
  hornetCount: 3,
  hornetLungeFreq: 0.9,
  hornetStandoff: 9.5,
  hornetLunge: 5.0,
  narrowInset: 0.42,
  narrowThickness: 1.1,
  retreatUp: 26.0,
  retreatBack: 12.0,
  retreatLead: 8.0,
  streamCount: 22,
  streamSpeed: 0.42,
  flourishBack: 0.72,
  flourishHigh: 0.86,
  flourishLook: 0.5,
  orbitCount: 40,
  orbitRadius: 0.34,
  orbitRise: 0.55,
  orbitSpeed: 0.22,
  combGrowFrom: 42.6,
  combGrowSpan: 3.6,
  combGrowStagger: 0.62,
  moteCount: 90,
  moteSpread: 1.5,
  moteRise: 2.2,
  moteLife: 1.6,
  moteSize: 0.075,
  workerMax: 72,
  hornetMax: 6,
  combMax: 420,
  workerLength: 0.62,
  hornetLength: 1.55,
  queenWingIdle: 0.05,
  queenWingFly: 0.85,
  interiorGain: 1.15,
  siegeDim: 0.42,
  flourishLight: 1.3,
  duskTime: 0.3,
  dayTime: 0.58,
  colors: {
    worker: 0xe0a03c,
    workerDark: 0x2a1c0e,
    workerWing: 0xdfe8f4,
    guard: 0xf0b955,
    hornet: 0xd6892a,
    hornetDark: 0x1a120a,
    hornetWing: 0xc8b8a0,
    wax: 0xd9a44e,
    waxDeep: 0x8a6224,
    waxFresh: 0xf0c268,
    cap: 0xe9c887,
    narrowing: 0x5a3a1e,
    mote: 0xffd98a,
  },
};
