// Hollowtree — audio tuning constants: mix levels, seasonal ambience weights, wing-buzz response curves, interior acoustics and weather layers.

export const AUDIO = {
  basePath: 'assets/audio/',
  loopTrim: 0.03,
  fadeIn: 1.6,
  crossfade: 1.1,
  insideFade: 0.18,
  refDistance: 6,
  maxDistance: 140,
  rolloff: 1.35,

  volumes: {
    master: 0.9,
    ambience: 0.85,
    sfx: 0.9,
    music: 0.7,
  },

  space: {
    outsideCutoff: 20000,
    insideCutoff: 1150,
    outsideHighpass: 20,
    insideHighpass: 105,
    wetOutside: 0.02,
    wetInside: 0.5,
    dryInside: 0.72,
    preDelay: 0.014,
    taps: [0.0231, 0.0313, 0.0411, 0.0577],
    feedback: 0.66,
    damping: 2400,
    spread: 0.55,
  },

  ambience: {
    layers: {
      meadow: { id: 'amb-meadow', gain: 1.0 },
      birds: { id: 'amb-birds', gain: 0.85 },
      cicadas: { id: 'amb-cicadas', gain: 0.8 },
      windCalm: { id: 'amb-wind-calm', gain: 0.9 },
      windForest: { id: 'amb-wind-forest', gain: 0.75 },
      night: { id: 'amb-night', gain: 0.95 },
      hollow: { id: 'amb-hollow', gain: 1.0 },
      hive: { id: 'bee-hive', gain: 0.7 },
    },
    seasons: {
      spring: { meadow: 0.92, birds: 0.9, cicadas: 0.0, windCalm: 0.22, windForest: 0.1 },
      summer: { meadow: 1.0, birds: 0.42, cicadas: 0.72, windCalm: 0.1, windForest: 0.05 },
      autumn: { meadow: 0.52, birds: 0.28, cicadas: 0.14, windCalm: 0.58, windForest: 0.46 },
      winter: { meadow: 0.1, birds: 0.06, cicadas: 0.0, windCalm: 0.82, windForest: 0.52 },
    },
    dawn: 0.24,
    dusk: 0.8,
    twilight: 0.07,
    nightFloor: 0.12,
    nightLevel: 0.95,
    duskWarmth: 0.28,
    seasonGlide: 2.6,
    dayGlide: 0.9,
    outsideDuck: 0.9,
    hollowRise: 1.0,
    hiveRise: 0.85,
    hiveSwarmBoost: 0.5,
  },

  wings: {
    voices: [
      { id: 'bee-wing-a', rate: 1.0, gain: 1.0, detune: 0 },
      { id: 'bee-wing-b', rate: 0.93, gain: 0.55, detune: -14 },
      { id: 'bee-swarm', rate: 1.04, gain: 0.0, detune: 9, swarm: 1.0 },
      { id: 'bee-swarm', rate: 0.82, gain: 0.0, detune: -21, swarm: 0.75 },
    ],
    idleGain: 0.3,
    speedGain: 0.72,
    maxSpeed: 16,
    ratePitch: 0.3,
    rateIdle: 0.88,
    wobbleRate: 0.9,
    wobbleDepth: 0.035,
    cutoffIdle: 2400,
    cutoffFast: 7200,
    swarmRef: 60,
    swarmMax: 200,
    swarmGain: 0.95,
    swarmPitchDrop: 0.16,
    swarmSpread: 0.5,
    insideBoost: 0.25,
    glide: 0.14,
    gain: 0.55,
  },

  gather: {
    id: 'sfx-gather-loop',
    gain: 0.7,
    rise: 0.22,
    fall: 0.4,
    cutoffLow: 900,
    cutoffHigh: 4200,
    rateLow: 0.88,
    rateHigh: 1.12,
  },

  weather: {
    layers: {
      rain: { id: 'wx-rain-light', gain: 1.0 },
      rainHeavy: { id: 'wx-rain-heavy', gain: 1.0 },
      rainInside: { id: 'wx-rain-inside-light', gain: 0.9 },
      rainInsideHeavy: { id: 'wx-rain-inside-heavy', gain: 0.9 },
      gale: { id: 'wx-wind-gale', gain: 0.8 },
    },
    glide: 1.4,
    kinds: {
      clear: { rain: 0, rainHeavy: 0, gale: 0, wind: 0, damp: 0 },
      overcast: { rain: 0, rainHeavy: 0, gale: 0.06, wind: 0.15, damp: 0.08 },
      fog: { rain: 0, rainHeavy: 0, gale: 0.04, wind: 0.1, damp: 0.35 },
      wind: { rain: 0, rainHeavy: 0, gale: 0.45, wind: 0.7, damp: 0.1 },
      rain: { rain: 0.85, rainHeavy: 0.18, gale: 0.1, wind: 0.2, damp: 0.22 },
      storm: { rain: 0.55, rainHeavy: 0.95, gale: 0.7, wind: 0.6, damp: 0.3 },
    },
    thunder: {
      ids: ['wx-thunder-1', 'wx-thunder-2', 'wx-thunder-3', 'wx-thunder-4'],
      storm: [7, 21],
      rain: [26, 70],
      gain: 0.85,
      indoorDuck: 0.55,
      rateRange: [0.86, 1.1],
      speedOfSound: 343,
      maxDelay: 6,
      bands: [
        { maxDistance: 90, id: 'wx-thunder-1', gain: 1.0, cutoff: 20000, rate: 1.0, offset: 0 },
        { maxDistance: 200, id: 'wx-thunder-3', gain: 0.78, cutoff: 7000, rate: 0.97, offset: 0 },
        { maxDistance: 360, id: 'wx-thunder-4', gain: 0.6, cutoff: 3400, rate: 0.93, offset: 1.4 },
        { maxDistance: Infinity, id: 'wx-thunder-2', gain: 0.45, cutoff: 1500, rate: 0.9, offset: 4.6 },
      ],
      distanceFalloff: 0.55,
      distanceRef: 60,
    },
    dampCutoff: 5200,
  },

  hornet: {
    droneId: 'hornet-drone',
    buzzId: 'hornet-buzz',
    gain: 0.8,
    glide: 1.8,
  },

  music: {
    tracks: {
      season: { id: 'music-season', gain: 0.9, fadeIn: 0.6, fadeOut: 2.4 },
      discovery: { id: 'music-discovery', gain: 0.85, fadeIn: 2.2, fadeOut: 4.0 },
      hollow: { id: 'music-discovery', gain: 0.85, fadeIn: 2.2, fadeOut: 4.0 },
      cutscene: { id: 'cutscene-music', gain: 1.0, fadeIn: 1.2, fadeOut: 3.0 },
    },
    minGap: 40,
    duckAmbience: 0.62,
    duckGlide: 1.2,
  },

  oneShots: {
    deposit: { id: 'sfx-deposit', gain: 0.85, spread: 0.02 },
    pickup: { id: 'sfx-pickup', gain: 0.55, spread: 0.06 },
    full: { id: 'sfx-full', gain: 0.7, spread: 0.02 },
    build: { id: 'sfx-build', gain: 0.75, spread: 0.05 },
    click: { id: 'sfx-click', gain: 0.45, spread: 0.02 },
    tick: { id: 'sfx-tick', gain: 0.35, spread: 0.04 },
    open: { id: 'sfx-open', gain: 0.6, spread: 0.02 },
    close: { id: 'sfx-close', gain: 0.6, spread: 0.02 },
    denied: { id: 'sfx-denied', gain: 0.55, spread: 0.02 },
    shimmer: { id: 'sfx-shimmer', gain: 0.6, spread: 0.05 },
    hornet: { id: 'hornet-buzz', gain: 0.9, spread: 0.08 },
    thunder: { id: 'wx-thunder-1', gain: 0.85, spread: 0.06 },
  },

  manifest: {
    'amb-meadow': { file: 'amb-meadow.mp3', core: true, loop: true },
    'amb-birds': { file: 'amb-birds.mp3', core: true, loop: true },
    'amb-cicadas': { file: 'amb-cicadas.mp3', loop: true },
    'amb-wind-calm': { file: 'amb-wind-calm.mp3', core: true, loop: true },
    'amb-wind-forest': { file: 'amb-wind-forest.mp3', loop: true },
    'amb-night': { file: 'amb-night.mp3', loop: true },
    'amb-hollow': { file: 'amb-hollow.mp3', core: true, loop: true },
    'bee-hive': { file: 'bee-hive.mp3', core: true, loop: true },
    'bee-wing-a': { file: 'bee-wing-a.mp3', core: true, loop: true },
    'bee-wing-b': { file: 'bee-wing-b.mp3', core: true, loop: true },
    'bee-swarm': { file: 'bee-swarm.mp3', core: true, loop: true },
    'hornet-drone': { file: 'hornet-drone.mp3', loop: true },
    'hornet-buzz': { file: 'hornet-buzz.mp3' },
    'wx-rain-light': { file: 'wx-rain-light.mp3', loop: true },
    'wx-rain-heavy': { file: 'wx-rain-heavy.mp3', loop: true },
    'wx-rain-inside-light': { file: 'wx-rain-inside-light.mp3', loop: true },
    'wx-rain-inside-heavy': { file: 'wx-rain-inside-heavy.mp3', loop: true },
    'wx-wind-gale': { file: 'wx-wind-gale.mp3', loop: true },
    'wx-thunder-1': { file: 'wx-thunder-1.mp3' },
    'wx-thunder-2': { file: 'wx-thunder-2.mp3' },
    'wx-thunder-3': { file: 'wx-thunder-3.mp3' },
    'wx-thunder-4': { file: 'wx-thunder-4.mp3' },
    'sfx-gather-loop': { file: 'sfx-gather-loop.mp3', core: true, loop: true },
    'sfx-shimmer': { file: 'sfx-shimmer.mp3' },
    'sfx-deposit': { file: 'sfx-deposit.mp3', core: true },
    'sfx-pickup': { file: 'sfx-pickup.mp3', core: true },
    'sfx-click': { file: 'sfx-click.mp3', core: true },
    'sfx-full': { file: 'sfx-full.mp3', core: true },
    'sfx-build': { file: 'sfx-build.mp3' },
    'sfx-open': { file: 'sfx-open.mp3' },
    'sfx-close': { file: 'sfx-close.mp3' },
    'sfx-denied': { file: 'sfx-denied.mp3' },
    'sfx-tick': { file: 'sfx-tick.mp3' },
    'music-season': { file: 'music-season.mp3' },
    'music-discovery': { file: 'music-discovery.mp3' },
    'cutscene-music': { file: 'cutscene-music.mp3' },
  },
};

export default AUDIO;
